name: Integration Tests

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of integration test to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - full-conversion-suite
        - lfq-only
        - tmt-only

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 1 hour timeout for the entire job
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install poetry
        # Install package in development mode
        poetry install
        
    - name: Run Full Conversion Suite Tests
      if: ${{ github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'full-conversion-suite' || github.event_name == 'release' }}
      run: |
        poetry run pytest -vv tests/test_full_conversion_suite.py --timeout=900
      env:
        PYTHONIOENCODING: utf-8
        
    - name: Run LFQ Tests Only
      if: ${{ github.event.inputs.test_type == 'lfq-only' }}
      run: |
        poetry run pytest -vv tests/test_full_conversion_suite.py -k "lfq" --timeout=900
      env:
        PYTHONIOENCODING: utf-8
        
    - name: Run TMT Tests Only  
      if: ${{ github.event.inputs.test_type == 'tmt-only' }}
      run: |
        poetry run pytest -vv tests/test_full_conversion_suite.py -k "tmt" --timeout=900
      env:
        PYTHONIOENCODING: utf-8
        
    - name: Run All Integration Tests
      if: ${{ github.event.inputs.test_type == 'all' || github.event_name == 'release' }}
      run: |
        poetry run pytest -vv -m "integration" --timeout=900
      env:
        PYTHONIOENCODING: utf-8 