"""Build script for ontology Parquet files.

Downloads OBO files from upstream sources (PSI-MS, PRIDE CV), parses them,
and writes Parquet files to two locations:

    1. ``data/ontology/`` at the repo root (checked into git, NOT shipped in pip)
    2. ``qpx/core/ontology/data/`` (bundled with the pip package as fallback)

Also updates ``data/ontology/versions.yaml`` with version, build time,
SHA-256 checksum, and term count for each source.

Usage::

    # Build a single source
    python -m qpx.core.ontology.build --source psi_ms

    # Build all configured sources
    python -m qpx.core.ontology.build --all
"""

from __future__ import annotations

import argparse
import hashlib
import logging
from datetime import datetime, timezone
from pathlib import Path

import yaml

from qpx.core.obo import (
    download_obo,
    extract_obo_version,
    parse_obo,
    write_terms_parquet,
)

logger = logging.getLogger(__name__)

_THIS_DIR = Path(__file__).resolve().parent
_SOURCES_PATH = _THIS_DIR / "sources.yaml"


def _find_repo_root() -> Path:
    """Walk up from this file to find the repository root.

    Looks for a directory containing ``mkdocs.yml`` or ``.git``.
    """
    current = _THIS_DIR
    for _ in range(10):
        if (current / "mkdocs.yml").is_file() or (current / ".git").is_dir():
            return current
        parent = current.parent
        if parent == current:
            break
        current = parent
    raise RuntimeError(
        "Could not locate repository root from %s. Run this script from within the quantms.io checkout." % _THIS_DIR
    )


def _load_sources_config() -> dict:
    """Load sources.yaml shipped with the package."""
    with open(_SOURCES_PATH, encoding="utf-8") as f:
        return yaml.safe_load(f)


def _sha256(path: Path) -> str:
    """Compute the SHA-256 hex digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _load_versions(versions_path: Path) -> dict:
    """Load an existing versions.yaml, or return an empty dict."""
    if versions_path.is_file():
        with open(versions_path) as f:
            data = yaml.safe_load(f)
            return data if isinstance(data, dict) else {}
    return {}


def _save_versions(versions_path: Path, data: dict) -> None:
    """Write versions.yaml with a human-readable header."""
    versions_path.parent.mkdir(parents=True, exist_ok=True)
    with open(versions_path, "w") as f:
        f.write("# Auto-generated by qpx.core.ontology.build\n")
        f.write("# Do not edit manually.\n\n")
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)


# ---------------------------------------------------------------------------
# Core build logic
# ---------------------------------------------------------------------------


def build_ontology(source_name: str, config: dict) -> dict:
    """Build a single ontology source: download, parse, write Parquet.

    Args:
        source_name: Key in the ``ontologies`` section of sources.yaml
            (e.g., ``"psi_ms"`` or ``"pride_cv"``).
        config: The full parsed sources.yaml dict.

    Returns:
        A dict with ``version``, ``built_at``, ``sha256``, and ``num_terms``
        suitable for insertion into versions.yaml.
    """
    ontologies = config.get("ontologies", {})
    if source_name not in ontologies:
        raise ValueError(f"Unknown source '{source_name}'. Available: {list(ontologies.keys())}")

    entry = ontologies[source_name]
    obo_url = entry["obo_url"]
    source_prefix = entry["source_prefix"]
    display_name = entry.get("display_name", source_name)

    print(f"[build] {display_name}")
    print(f"        Downloading {obo_url} ...")

    # 1. Download OBO
    text = download_obo(obo_url, timeout=60)
    version = extract_obo_version(text)
    print(f"        Version: {version}")

    # 2. Parse
    terms = parse_obo(text, source=source_prefix)
    print(f"        Parsed {len(terms)} terms")

    # 3. Determine output paths
    repo_root = _find_repo_root()
    repo_data_dir = repo_root / "data" / "ontology"
    pkg_data_dir = _THIS_DIR / "data"

    repo_parquet = repo_data_dir / f"{source_name}.parquet"
    pkg_parquet = pkg_data_dir / f"{source_name}.parquet"

    # 4. Write Parquet to both locations
    write_terms_parquet(terms, repo_parquet, source=source_name, version=version)
    print(f"        Wrote {repo_parquet}")

    write_terms_parquet(terms, pkg_parquet, source=source_name, version=version)
    print(f"        Wrote {pkg_parquet}")

    # 5. Compute checksum (use repo copy as canonical)
    checksum = _sha256(repo_parquet)
    built_at = datetime.now(timezone.utc).isoformat()

    result = {
        "version": version,
        "built_at": built_at,
        "sha256": checksum,
        "num_terms": len(terms),
    }

    print(f"        SHA-256: {checksum}")
    print("        Done.\n")

    return result


def build_all(config: dict) -> dict[str, dict]:
    """Build all ontology sources defined in sources.yaml.

    Returns:
        A dict mapping source names to their version metadata.
    """
    ontologies = config.get("ontologies", {})
    results = {}
    for source_name in ontologies:
        results[source_name] = build_ontology(source_name, config)
    return results


def main(argv: list[str] | None = None) -> None:
    """Entry point for ``python -m qpx.core.ontology.build``."""
    parser = argparse.ArgumentParser(
        prog="python -m qpx.core.ontology.build",
        description="Build ontology Parquet files from upstream OBO sources.",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--source",
        type=str,
        help="Build a single source (e.g., psi_ms, pride_cv).",
    )
    group.add_argument(
        "--all",
        action="store_true",
        dest="build_all",
        help="Build all configured ontology sources.",
    )

    args = parser.parse_args(argv)
    config = _load_sources_config()

    # Resolve versions.yaml path
    repo_root = _find_repo_root()
    versions_path = repo_root / "data" / "ontology" / "versions.yaml"
    versions = _load_versions(versions_path)

    if args.build_all:
        results = build_all(config)
        versions.update(results)
    else:
        result = build_ontology(args.source, config)
        versions[args.source] = result

    # Write versions.yaml
    _save_versions(versions_path, versions)
    print(f"[build] Updated {versions_path}")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    main()
